name: Deploy Github Pages

on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: windows-latest

        steps:
          - name: Reset and Clean Repository
            run: |
              git reset --hard
              git clean -fdx
          - uses: actions/checkout@v3
            
          - name: Deploy to Github Pages
            uses: peaceiris/actions-gh-pages@v3
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./
